service=whostmgr
displayname=TRNOG Outbound Monitor
url=/cgi/trnog_outbound_monitor.cgi/embed/whm
entryurl=cgi/trnog_outbound_monitor.cgi/embed/whm
icon=trnog-outbound-monitor.png
acls=all
target=_self
searchtext=trnog outbound logger ebpf outbound monitor security traffic
